### PR TITLE
Fix #6 - Bump robfig/cron to v3

### LINKED ISSUE #6: Please update github.com/robfig/cron to v3
From their documentation:
> The v1 branch accepted an optional seconds field at the beginning of the cron spec. This is non-standard and has led to a lot of confusion. The new default parser conforms to the standard as described by the Cron wikipedia page.

Problem I am facing is, expression `* * * * *` should be interpreted as [once per minute](https://crontab.guru/every-minute), however workflows are scheduled every second.

### PR DESCRIPTION
**Pull request by tomasol**

### CODE REVIEW

**Comment by flaviostutz** [comment]
Great enhancements to the code! Thanks!

**Comment by flaviostutz** [comment]
@tomasol I just got curious here. Which type of project are you using schellar?

**Comment by flaviostutz** [comment]
Ah... I've just tagged codebase with with contribution so that you can reference the new container with flaviostutz/schellar:1.4.0

**Comment by tomasol** [comment]
Thanks for quick merge and especially the release, I appreciate it!
Sadly the project is not open source yet, I will let you know when it becomes public.

**Comment by flaviostutz** [comment]
Great ;)

**Pull request merged**
